#!/usr/bin/env python3

## 1. @staticmethod: Usando un numero, variable y una instancia para obtener al juego GOTY. 
#
def p1():
    class Triangle:
        goty = 7 

        def __init__(self, base, height, best=7):
            self.base = base
            self.height = height
            self.best = best

        @staticmethod # Opcion usando directamente un numero.
        def game_1(review):
            return review > 7
    
        @staticmethod # Opcion usando la variable "goty".
        def game_2(review):
            return review > Triangle.goty

        @staticmethod # Opcion usando una instancia + cambio de codigo para retornar.
        def game_3(instancia, review):
            return review > instancia.best

    triangle_obj_1 = Triangle(3, 5)
    print(f"\n[#] 1.¿GOTY? -> {Triangle.game_1(9)}")
    print(f"\n[#] 2.¿GOTY? -> {Triangle.game_2(9)}")
    print(f"\n[#] 3.¿GOTY? -> {Triangle.game_3(triangle_obj_1, 9)}")

## 2. @staticmethod:
#

def p2():
    class Calculator:

        @staticmethod
        def sum(num1, num2):
            return num1 + num2

        @staticmethod
        def minus(num1, num2):
            return num1 - num2 

        @staticmethod
        def division(num1, num2):
            return num1 // num2 if num2 != 0 else f"\n[!] Error: No es posible dividir entre 0."

        @staticmethod
        def multiplication(num1, num2):
            return num1 * num2

    print(f"\n[#] Suma: {Calculator.sum(5, 4)}.")
    print(f"\n[#] Resta: {Calculator.minus(5, 4)}.")
    print(f"\n[#] Division: {Calculator.division(10, 5)}.")
    print(f"\n[#] multiplication: {Calculator.multiplication(10, 5)}.")

def p3():
    class Automovil:
        def __init__(self, marca, modelo):
            self.marca =  marca
            self.modelo = modelo

        @classmethod 
        def deportivos(cls, marca):
            return cls(marca, "Deportivo")

        @classmethod 
        def clasicos(cls, marca):
            return cls(marca, "Deportivo")

        def __str__(self):
            return f"\n[#] Marca: {self.marca}; Modelo: {self.modelo}."
        
    objeto_1 = Automovil.deportivos("Ferrari")
    print(objeto_1)

    objeto_2 = Automovil.clasicos("Mustang")
    print(objeto_2)

def p4():
    class Estudiantes:

        estudiantes = []

        def __init__(self, nombre, edad):
            self.nombre = nombre
            self.edad = edad

            Estudiantes.estudiantes.append(self)
        
        @staticmethod
        def es_mayor_de_edad(edad):
            return edad >= 18

        @classmethod
        def crear_estudiantes(cls, nombre, edad):
            if cls.es_mayor_de_edad(edad):
                return cls(nombre, edad)
            else:
                print(f"\n[!] El estudiante {nombre} es menor edad.")
        
        @staticmethod
        def mostrar_estudiantes():
            print(f"\n[#] Estudiantes mayores de edad:.\n")
            for i, alumnos in enumerate(Estudiantes.estudiantes):
                print(f"\t[{i}] {alumnos.nombre}.")

    Estudiantes.crear_estudiantes("Hackermate", 43)
    Estudiantes.crear_estudiantes("S4vitar", 28)
    Estudiantes.crear_estudiantes("Xerosec", 12)
    Estudiantes.crear_estudiantes("Hackavis", 8)

    Estudiantes.mostrar_estudiantes()












