#!/usr/bin/env python3

## 0 Notacion []:
def p0():
    mi_lista = ['arbol', 'casa', 'pato']
    elemento = mi_lista[0]
    print(elemento)

## 1. Metodo index:
def p1():
    mi_lista = ['arbol', 'casa', 'pato']
    indice = mi_lista.index('casa')
    print(indice)

## 2. Metodo Apppend: 
def p2():
    mi_lista = [1, 2, 3]
    mi_lista.append(4)
    print(mi_lista)

## 3. Operacion mas igual: 
def p3():
    mi_lista = [1, 2, 3]
    mi_lista += [4, 5, 6]
    print(mi_lista)

## 4. Metodo insert:
def p4():
    mi_lista = [1, 2, 3]
    mi_lista.insert(0, 99)
    print(mi_lista)

## 5. Metodo sort:
def p5():
    mi_lista = [2, 1, 3]
    mi_lista.sort()
    print(mi_lista)

## 6. Sentencia del:
def p6():
    mi_lista = [2, 1, 3]
    del mi_lista[0]
    print(mi_lista)

## 7. Metodo pop:
def p7():
    mi_lista = [2, 1, 3]
    mi_lista.pop()
    print(mi_lista)
    
## 8. Metodo remove:
def p8():
    mi_lista = ["arbol", "casa", "roca"]
    mi_lista.remove("casa")
    print(mi_lista)

## 9. Funcion set:
def p9():
    mi_lista = [1, 1, 1, 1, 1, 2]
    agrupamiento = set(mi_lista)
    print(agrupamiento)

## 10. Funcion len:
def p10():
    mi_lista = ["arbol", "casa", "roca"]
    total = len(mi_lista)
    print(total)

## 11. Metodo count:
def p11():
    mi_lista = [1, 1, 1, 1, 1, 2]
    repetido = mi_lista.count(1)
    print(repetido)


## 12. Funcion sum:
def p12():
    mi_lista = [1, 2]
    suma = sum(mi_lista)
    #suma = mi_lista.sum()
    print(suma)

## 13. Funcion min:
def p13():
    mi_lista = [1, 2]
    minimo = min(mi_lista)
    print(minimo)

## 14. Funcion max:
def p14():
    mi_lista = [1, 2]
    maximo = max(mi_lista)
    print(maximo)

## 15. Metodo reverse:
def p15():
    mi_lista = [1, 2, 3]
    mi_lista.reverse() 
    print(mi_lista)

