#!/usr/bin/env python3

## 1. Notacion []:
def p1():
    mi_lista = ['arbol', 'casa', 'pato']
    elemento = mi_lista[0]
    print(elemento)

## 2. Metodo index:
def p2():
    mi_lista = ['arbol', 'casa', 'pato']
    indice = mi_lista.index('casa')
    print(indice)

## 3. Metodo Apppend: 
def p3():
    mi_lista = [1, 2, 3]
    mi_lista.append(4)
    print(mi_lista)

## 4. Operacion mas igual: 
def p4():
    mi_lista = [1, 2, 3]
    mi_lista += [4, 5, 6]
    print(mi_lista)

## 5. Metodo insert:
def p5():
    mi_lista = [1, 2, 3]
    mi_lista.insert(0, 99)
    print(mi_lista)

## 6. Metodo sort:
def p6():
    mi_lista = [2, 1, 3]
    mi_lista.sort()
    print(mi_lista)

## 7. Sentencia del:
def p7():
    mi_lista = [2, 1, 3]
    del mi_lista[0]
    print(mi_lista)

## 8. Metodo pop:
def p8():
    mi_lista = [2, 1, 3]
    mi_lista.pop()
    print(mi_lista)
    
## 9. Metodo remove:
def p9():
    mi_lista = ["arbol", "casa", "roca"]
    mi_lista.remove("casa")
    print(mi_lista)

## 10. Funcion set:
def p10():
    mi_lista = [1, 1, 1, 1, 1, 2]
    agrupamiento = set(mi_lista)
    print(agrupamiento)

## 11. Funcion len:
def p11():
    mi_lista = ["arbol", "casa", "roca"]
    total = len(mi_lista)
    print(total)

## 12. Metodo count:
def p12():
    mi_lista = [1, 1, 1, 1, 1, 2]
    repetido = mi_lista.count(1)
    print(repetido)


## 13. Funcion sum, min y max:
def p13():
    mi_lista = [1, 2, 3]
    resultado_suma = sum(mi_lista)
    resultado_minimo = min(mi_lista)
    resultado_maximo = max(mi_lista)
    print(resultado_suma)
    print(resultado_minimo)
    print(resultado_maximo)

## 14. Metodo reverse:
def p14():
    mi_lista = [1, 2, 3]
    mi_lista.reverse() 
    print(mi_lista)

## 15. Desenpaquetado:
def p15():
    elementos = [1, 2, 3]
    a, b, c = elementos
    print(c, b, a)

## 16. Metodo clear:
def p16():
    mi_lista = [1, 2, 3, 4, 5, 6, 7, 8 , 9, 10]
    mi_lista.clear()
    print(mi_lista)

## 17. Metodo extend:
def p17():
    lista_1 = [1, 2]
    lista_2 = [3, 4] 
    lista_1.extend(lista_2)
    print(lista_1)
