#!/usr/bin/env python3

## 1. Bucle for: Mostrar el indice y los elementos de la lista.
def p1():
    casas = ["pequeña", "mediana", "grande"]
    for x, y in enumerate(casas):
        print(f"Slot [{x+1}]: {y}")

## 2. Bucle for: Aplicando "for" en un diccionarios usando "items", "keys" y "values". 
def p2():
    my_dict = {'Pato': 1, 'Gato': 2, 'Perro': 3}
    for i, y in my_dict.items():
        print(i, y)
    print()

    for i in my_dict.keys():
        print(i)
    print()

    for i in my_dict.values():
        print(i)
    print()

## 3. Bucle for: Aplicando "for" en una listas dentro de otra lista.
def p3():
    my_list = [[1, 2], [3, 4]]
    for i in my_list:
        for x in i:
            print(x)

## 4. Bucle for: Aplicando potencias a los elementos de una lista(1 linea para luego print).
def p4():
    list_num = [2, 4, 5]
    cuad = [i ** 2 for i in list_num]
    print(cuad)


## 5. Bucle for: Uso del zip en 2 listas.
def p5():
    alumnos = ["Juan", "Pascual", "Ariel"]
    edades = [18, 13, 15]
    for alumno, edad in zip(alumnos, edades):
        print(f"Alumno: {alumno}; Edad: {edad}")
