#!/usr/bin/env python3

## 1. remove: Quitar un elemento por su valor.
def p1():
    my_set = {1, 2, 3}
    my_set.remove(3)
    print(my_set)

## 2. discard: Quitar un elemento por su valor y ademas evitando errores.
def p2():
    my_set = {1, 2, 3}
    my_set.discard(4)
    my_set.discard(3)
    print(my_set)

## 3. add: Agregar un elemento.
def p3():
    my_set = {1, 2, 3}
    my_set.add(8)
    print(my_set)

## 4. update: Agregar varios elementos.
def p4():
    my_set = {1, 2, 3}
    my_set.update({2, 4, 5, 8})
    print(my_set)

## 5. Union: Unir 2 conjuntos quitando repetidos(No modifica directamente).
def p5():
    my_set_1 = {1, 2, 3, 4, 5}
    my_set_2 = {1, 2, 4, 5}
    union = my_set_1.union(my_set_2)
    print(union)

## 6. intersection: Muestra los valores repetidos(1^ conjunto).
def p6():
    my_set_1 = {1, 2, 3}
    my_set_2 = {3, 5, 6}
    result = my_set_1.intersection(my_set_2)
    print(result)

## 7. difference: Muestra los valores no repetidos(1^ conjunto).
def p7():
    my_set_1 = {1, 2, 3}
    my_set_2 = {3, 5, 6}
    result = my_set_1.difference(my_set_2)
    print(result)

## 8. Issubset: True or false. ¿Se repiten todos los valores?(1^ conjunto).
def p8():
    my_set_1 = {1, 2, 3}
    my_set_2 = {1, 2, 3, 4}
    result = my_set_1.issubset(my_set_2)
    print(result)

## 9. Clear:
def p9():
    my_set_1 = {1, 2, 3}
    my_set_1.clear()
    print(my_set_1)
