#!/usr/bin/env python3

## 1. Notacion []: Mostrar el valor de la clave.
def p1():
    my_dictionary = {"Pera": 9, "Manzana": 4, "Zandia": 7}
    print(my_dictionary["Pera"])

## 2. Mostrar el valor del diccionario dentro de otro diccionario.
def p2():
    my_dict = {"Manzana": {"europea": 3, "asiatica": 5}, "Pera": 2}
    result = my_dict["Manzana"]["europea"]
    print(result)

## 3. Mostrar las keys y values por medio de prints.
def p3():
    my_dict = {"Manzana": 3, "Pera": 2}
    print(my_dict.keys())
    print(my_dict.values())

## 4. Eliminar elementos.
def p4():
    my_dict = {"Manzana": 3, "Pera": 2}
    my_dict.pop("Manzana")
    print(my_dict)

## 5. Agregar elementos. 
def p5():
    my_dictionary = {"Pera": 9, "Manzana": 4, "Zandia": 7}
    my_dictionary["Banana"] = 12
    print(my_dictionary)

## 6. Actualizar valores.
def p6():
    my_dict = {"Manzana": 3, "Pera": 2}
    my_dict["Manzana"] = 5
    print(my_dict)

## 7. Len: Cuenta cada elemento.
def p7():
    my_dictionary = {"Pera": 9, "Manzana": 4, "Zandia": 7}
    longitud = len(my_dictionary)
    print(longitud)

## 8. Get: Buscar el valor de la clave pero en caso contrario hacer lo siguiente.
def p8():
    my_dictionary = {"Pera": 9, "Manzana": 4, "Zandia": 7}
    busqueda = my_dictionary.get("Limon", "No encontrado.")
    print(busqueda)

## 9. Clear: 
def p9():
    my_dictionary = {"Pera": 9, "Manzana": 4, "Zandia": 7}
    my_dictionary.clear()
    print(my_dictionary)
