#!/usr/bin/env python3
import os
import sys

# Global
clear_screen = lambda: os.system("clear")

class Bank:
    def __init__(self, id, nombre_completo, saldo):
        self.id = id
        self.nombre_completo = nombre_completo
        self.saldo= saldo

    def estado(self):
        clear_screen()
        print(f"\n[#] ---Bank Shuk: Cuenta---\n")
        print(f"[=] Id: {self.id}")
        print(f"[#] Usuario {self.nombre_completo}: activo")
        print(f"[=] Saldo: {self.saldo}\n")
    def depositar(self, dar):
        clear_screen() 
        self.saldo += dar
        print(f"\n[#] ---Bank Shuk: Saldo---\n")
        print(f"[+] Depositado: {dar}; [!] Saldo: {self.saldo}\n")
    def retirar(self, sacar):
        clear_screen() 
        self.saldo -= sacar
        print(f"\n[#] ---Bank Shuk: Saldo---\n")
        print(f"[-] Retirado: {sacar}; [!] Saldo: {self.saldo}\n")

obj = Bank(1234, "Juan Perez", 44000)

def show_menu_1():
    print("\n[#] ---Bank Star: Menu---\n")
    print("[*] 1) Estado.")
    print("[*] 2) Depositar.")
    print("[*] 3) Retirar.")
    print("[*] 4) Salir.\n")

def show_input(opcion):
    while True:
        if opcion == 4:
            sys.exit()
        elif opcion == 1:
            cuenta()
            show_menu_2()
        elif opcion == 2:
            entregar()
            show_menu_2()
        elif opcion == 3:
            extraer()
            show_menu_2()
        else:
            print("Error Fatal.")

def show_menu_2():
    while True:
        print("[*] 1) Volver.")
        print("[*] 2) Salir.\n")
        obj = int(input())
        if obj == 1:
            clear_screen() 
            show_menu_1()
            opcion = int(input())
            show_input(opcion)
        elif obj == 2:
            sys.exit()
        else:
            print("Error: valor incorrecto.")

def cuenta():
    clear_screen() 
    obj.estado()

def entregar():
    clear_screen() 
    print(f"\n[#] ---Bank Shuk: Operacion---\n")
    print("Monto a depositar: ")
    monto_entrada = int(input())
    obj.depositar(monto_entrada)

def extraer():
    clear_screen() 
    print(f"\n[#] ---Bank Shuk: Operacion---\n")
    print("Monto a retirar: ")
    monto_salida = int(input())
    obj.retirar(monto_salida)

while True:
    show_menu_1()
    opcion = int(input())
    show_input(opcion)
