#!/usr/bin/env python3

import os

clear_screen = lambda: os.system('clear')

player = [(1, 1)]
move = ['d', 'a']
door = (11, 1)

def board():
    for y in range(1, 0, -1):
        for x in range(1, 11):
            if (x, y) in player:
                print('#', end=' ')
            else:
                print('.', end=' ')
        print()


def move_player():
    global player
    x, y = player[0]
    if address == 'd':
        x += 1
    elif address == 'a':
        x -= 1

    player.insert(0, (x, y))
    player.pop()

    if player[0] == door:
        player = [(1, 1)]
    else:
        pass

def main():
    torch = 100
    while torch > 0:
        clear_screen()
        print(f'\n[#] Capacidad de la antorcha: {torch}')
        print(f'\n[#] - Masmorra - [#]\n')
        torch -= 1
        board()
        key = input('[*]: ').lower()
        if key in move:
            global address 
            address = key
            move_player()
    else:
        clear_screen()
        print(f'\n[!] Perdiste!.\n')

if __name__ == "__main__":
    main()

