#!/usr/bin/env python3
import random
import time
import os

ancho = 20
alto = 10

fruta = (random.randint(1, ancho), random.randint(1, alto))
vibora = [(alto // 2, ancho // 2)]

#    os.system("clear")
for y in range(1, alto + 1):
    for x in range(1, ancho + 1):
        if (x, y) in vibora:
            print("O", end=" ")
        elif (x, y) == fruta:
            print("P", end=" ")
        else:
            print('.', end=" ")
    print()
#    print()

print(fruta)
print(vibora)

