#!/bin/bash

## 1. Redireccionamiento con sobreescritura:
function p1() {
  echo "hola mundo" >script.sh
}

## 2. Redireccionamiento sin sobreescritura:
function p2() {
  echo "hola mundo" >>script.sh
}

## 3.
function p3() {
  echo "asd"
}

## 4.
function p4() {
  echo "asd"
}
