#!/bin/bash

## 1. Redireccionamiento con sobreescritura:
function p1() {
  echo "hola mundo" >script.sh
}

## 2. Redireccionamiento sin sobreescritura:
function p2() {
  echo "hola mundo" >>script.sh
}

## 3.
function p3() {
  echo "asd"
}

## 4.
function p4() {
  echo "asd"
}

## 5.
function p5() {
  echo "asd"
}

## 6.
function p6() {
  echo "asd"
}

## 7.
function p7() {
  echo "asd"
}

## 8.
function p8() {
  echo "asd"
}

## 9.
function p9() {
  echo "asd"
}

## 10.
function p10() {
  echo "asd"
}
