#!/bin/bash

## 1. Metodo manual: Agregar un usuario con ruta predeterminada + shell personalizada.
function p1() {
  sudo useradd ramon -m -s /bin/zsh
}

## 2. Metodo automatico: Agregar un usuario con ruta y shell predeterminada.
function p2() {
  sudo useradd ramon -m -s
}

## 3. Eliminacion: Elimina ademas del propio usuario a su propia ruta de manera forzada.
function p3() {
  sudo userdel -r ramon
}

## 4. Seguridad: Agregacion de contraseña.
function p4() {
  sudo passwd ramon
}

## 5.
function p5() {
  echo "asd"
}
